services:
  db:
    image: postgres:15-alpine
    container_name: crud_postgres
    environment:
      POSTGRES_USER: roveda
      POSTGRES_PASSWORD: roveda2025
      POSTGRES_DB: crud_db
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roveda -d crud_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: crud_api
    environment:
      DATABASE_URL: postgresql://roveda:roveda2025@db:5432/crud_db
    ports:
      - "8080:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
